GabinetStomatologiczny/GabinetStomatologiczny/Controllers/LekarzsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GabinetStomatologiczny.DAL;
using GabinetStomatologiczny.DAO.Models;
using System.IO;
using PagedList;
using GabinetStomatologiczny.Utils;
using GabinetStomatologiczny.Services;
using System.Threading.Tasks;

namespace GabinetStomatologiczny.Controllers
{
    [Authorize]
    public class LekarzsController : BaseController
    {

        private readonly ILekarzService _lekarzservice;
        private readonly ISortLekarzService _lekarzSortService;
        private readonly ISugestionService _sugestionService;
        public LekarzsController(ILekarzService lekarzservice, ISortLekarzService lekarzSortService,ISugestionService sugestionService)
        {
            this._lekarzservice = lekarzservice;
            this._lekarzSortService = lekarzSortService;
            this._sugestionService = sugestionService;
        }

        // GET: Lekarzs
        public ActionResult Index(LekarzSort lekarzSort)
        {
            ViewBag.CurrentSort = lekarzSort.sortOrder;
            if (string.IsNullOrEmpty(lekarzSort.searchString))
            {
                lekarzSort.searchString = lekarzSort.currentFilter;
            }

            ViewBag.CurrentFilter = lekarzSort.searchString;
            var lekarz = this._lekarzSortService.SortAndPaginate(lekarzSort);
            ViewBag.ActiveClass = this._lekarzSortService.RodzajSort;


            if (Request.IsAjaxRequest())
            {
                return PartialView("_LekarzsParts", lekarz);
            }
            return View(lekarz);
        }

        public ActionResult SugestionsLekarzs(Sugestion sugestion)
        {
            var list = this._sugestionService.SugestionLekarz(sugestion);

            return Json(list, JsonRequestBehavior.AllowGet);
        }


        // GET: Lekarzs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Lekarz lekarz = this._lekarzservice.Find(id);
            if (lekarz == null)
            {
                return HttpNotFound();
            }
            return View(lekarz);
        }

       
        // GET: Lekarzs/Create
        public ActionResult Create()
        {
           return View();
        }

        // POST: Lekarzs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Imie,Nazwisko,Zdjecie,Email,NrTelefonu")] Lekarz lekarz)
        {
            if (ModelState.IsValid)
            {
                this._lekarzservice.CreateLekarz(lekarz);
                return RedirectToAction("Index");
            }

            return View(lekarz);
        }

        // GET: Lekarzs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Lekarz lekarz = this._lekarzservice.Find(id);

            if (lekarz == null)
            {
                return HttpNotFound();
            }
            return View(lekarz);
        }

        // POST: Lekarzs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Imie,Nazwisko,Zdjecie,Email,NrTelefonu")] Lekarz lekarz)
        {
            
            if (ModelState.IsValid)
            {
                HttpPostedFileBase file = Request.Files["Zdjecie"];
                UpdateModel(lekarz);
                if (file != null && file.ContentLength > 0)
                {
                    lekarz.Zdjecie = System.Guid.NewGuid().ToString();
                    lekarz.Zdjecie = file.FileName;
                    file.SaveAs(HttpContext.Server.MapPath("~/Obrazki/") + lekarz.Zdjecie);
                }

                this._lekarzservice.Edit(lekarz);
                TempData["editLekarz"] = "done";
                return RedirectToAction("Index");
            }
            return View(lekarz);
        }

        // GET: Lekarzs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Lekarz lekarz = this._lekarzservice.Find(id);
            if (lekarz == null)
            {
                return HttpNotFound();
            }
            else if (!User.Identity.IsAuthenticated)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            return View(lekarz);
        }

        // POST: Lekarzs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Lekarz lekarz = db.Lekarz.Find(id);
            if(lekarz.Zdjecie != null)
            {
                string path = Request.MapPath("~/Obrazki/" + lekarz.Zdjecie);
                System.IO.File.Delete(path);
            }
            this._lekarzservice.Remove(lekarz);
            return RedirectToAction("Index");
        }

    }
}

GabinetStomatologiczny/GabinetStomatologiczny/Views/Lekarzs/Create.cshtml
@model GabinetStomatologiczny.DAO.Models.Lekarz

@{
    ViewBag.Title = "Utwórz";
}

<h2>@ViewBag.Title</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Lekarz</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Imie, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Imie, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Imie, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nazwisko, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nazwisko, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nazwisko, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Zdjecie, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Zdjecie, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Zdjecie, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="@ViewBag.Title" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
}

GabinetStomatologiczny/GabinetStomatologiczny/Views/Lekarzs/Delete.cshtml
@model GabinetStomatologiczny.DAO.Models.Lekarz

@{
    ViewBag.Title = "Kasuj";
}

<h2>Kasuj</h2>

<h3>Napewno chcesz skasować?</h3>
<div>
    <h4>Lekarz</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Imie)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Imie)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nazwisko)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nazwisko)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Zdjecie)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Zdjecie)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

GabinetStomatologiczny/GabinetStomatologiczny/Views/Lekarzs/Details.cshtml
@model GabinetStomatologiczny.DAO.Models.Lekarz

<link href="~/Content/Zdjecia.css" rel="stylesheet" />
@{
    ViewBag.Title = "Więcej";
}

<h2>Więcej informacji</h2>

<div>
    <h4>Lekarz</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Imie)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Imie)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nazwisko)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nazwisko)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Zdjecie)
        </dt>

        <dd>
            @if (Model.Zdjecie != null)
            {
                <img src="~/Obrazki/@Html.DisplayFor(modelItem => Model.Zdjecie)" id="myImg" class="rozmiar" />
                <div id="myModal" class="modal">
                    <span class="close">&times;</span>
                    <img class="modal-content" id="img01">
                    <div id="caption"></div>
                </div>
            }
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NrTelefonu)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NrTelefonu)
        </dd>

    </dl>
</div>
<p>
    @if (User.Identity.IsAuthenticated && User.Identity.Name == Model.Email)
    {
        @Html.ActionLink("Edycja", "Edit", new { id = Model.ID }, new { @class = "btn btn-info" })
        <span> | </span>
    }
    @Html.ActionLink(" Wstecz", "Index", null, new { @class = "glyphicon glyphicon-hand-left" })
</p>

@section scripts{
    <script src="~/Content/script/Zdjecia.js"></script>
}

GabinetStomatologiczny/GabinetStomatologiczny/Views/Lekarzs/Edit.cshtml
@model GabinetStomatologiczny.DAO.Models.Lekarz

@{
    ViewBag.Title = "Edycja";
}


<link href="~/Content/Zdjecia.css" rel="stylesheet" />


<h2> @ViewBag.Title</h2>



@using (Html.BeginForm("Edit", "Lekarzs", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Lekarz</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Imie, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Imie, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Imie, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nazwisko, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nazwisko, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nazwisko, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Zdjecie, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Zdjecie, new { htmlAttributes = new { @class = "form-control editOraz", type = "File" } })
                @Html.ValidationMessageFor(model => model.Zdjecie, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <div id="miniaturka"></div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NrTelefonu, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NrTelefonu, new { htmlAttributes = new { @class = "form-control", @id = "inputNumber", maxlength = "11" } })
                @Html.ValidationMessageFor(model => model.NrTelefonu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Zapisz" class="btn btn-block btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Wstecz", "Index",null,new {@class= "glyphicon glyphicon-hand-left" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Content/script/Zdjecia.js"></script>
    <script src="/Scripts/jquery-3.3.1.js"></script>
    <script src="~/Scripts/jquery-ui-1.12.1.js"></script>
    <script src="~/Content/script/FormatMask.js"></script>
}

GabinetStomatologiczny/GabinetStomatologiczny/Views/Lekarzs/Index.cshtml
@model PagedList.IPagedList<GabinetStomatologiczny.DAO.Models.Lekarz>
@{
    ViewBag.Title = "Lekarze";
    ViewBag.Active = "Pacjenci";
}

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link href="~/Content/Lekarzs.css" rel="stylesheet" />
<link href="@Url.Content("~/Content/Zdjecia.css")" rel="stylesheet" />
<link href="@Url.Content("~/Content/TableStyle.css")" rel="stylesheet" />
<link href="~/Content/Wyszukiwarka.css" rel="stylesheet" />
<link href="~/Content/themes/base/jquery-ui.css" rel="stylesheet" />

<h2>Lekarze</h2>

@if (TempData["editLekarz"] != null)
{
    <div class="alert alert-success alert-dismissible">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        Pomyślnie edytowano
    </div>
}

<div class="form-group">
    <form id="wyslij" class="wyszukiwarka" method="get" data-ajax="true">
        <span id="searchclear" class="glyphicon glyphicon-remove-circle kasujText kasujTextLekarz"></span>
        <input type="text" id="searchQuery" name="searchQuery" data-autocomplete-source="@Url.Action("SugestionsLekarzs")"
               placeholder="Wpisz min 1 znak" class="form-control lekarz-query" />
        <button type="submit" data-toggle="tooltip" title="Wyszukaj" class="szukajLekarzaAjax form-control"><i class="fa fa-search"></i></button>
    </form>
</div>

@Html.Partial("_LekarzsParts")

@section scripts{
    <script src="~/Content/script/WyszukiwanieAjaxowe.js"></script>
    <script src="~/Content/script/Zdjecia.js"></script>
    <script src="~/Scripts/jquery-ui-1.12.1.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script src="~/Content/script/AutoComplete.js"></script>
}

GabinetStomatologiczny/GabinetStomatologiczny/Views/Lekarzs/_LekarzsParts.cshtml
@model PagedList.IPagedList<GabinetStomatologiczny.DAO.Models.Lekarz>
@using PagedList.Mvc;
@using Microsoft.AspNet.Identity
@using GabinetStomatologiczny.DAO.Models;

<div class="ladowanie"></div>

@if (Model.Count > 0)
{
    <div class="data-select">
        <table class="table">
            <tr>
                <th>
                    Imie
                </th>
                <th>
                    Nazwisko
                </th>
                <th>
                    Zdjęcie
                </th>
                <th>
                    Telefon
                </th>
                <th>
                    Email
                </th>
                <th>
                    @Html.DisplayName("Akcja")
                </th>
            </tr>

            <tr>
                <td>
                    @Html.ActionLink("↑", "Index", new { sortOrder = RodzajSort.name_asc, currentFilter = ViewBag.CurrentFilter }
                    ,new {Class= @ViewBag.ActiveClass == RodzajSort.name_asc ? "active" : "", title="Rosnąco" })
                    @Html.ActionLink("↓", "Index", new { sortOrder = RodzajSort.name_desc, currentFilter = ViewBag.CurrentFilter }
                    , new { Class = @ViewBag.ActiveClass == RodzajSort.name_desc ? "active" : "", title = "Malejąco" })
                </td>
                <td>
                    @Html.ActionLink("↑", "Index", new { sortOrder = RodzajSort.surname_asc, currentFilter = ViewBag.CurrentFilter }
                    , new { Class = @ViewBag.ActiveClass == RodzajSort.surname_asc ? "active" : "", title = "Rosnąco" })
                    @Html.ActionLink("↓", "Index", new { sortOrder = RodzajSort.surname_desc, currentFilter = ViewBag.CurrentFilter }
                    , new { Class = @ViewBag.ActiveClass == RodzajSort.surname_desc ? "active" : "", title = "Malejąco" })
                </td>
                <td></td>
                <td>
                    @Html.ActionLink("↑", "Index", new { sortOrder = RodzajSort.nrtel_asc, currentFilter = ViewBag.CurrentFilter }
                    , new { Class = @ViewBag.ActiveClass == RodzajSort.nrtel_asc ? "active" : "", title = "Rosnąco" })
                    @Html.ActionLink("↓", "Index", new { sortOrder = RodzajSort.nrtel_desc, currentFilter = ViewBag.CurrentFilter }
                    , new { Class = @ViewBag.ActiveClass == RodzajSort.nrtel_desc ? "active" : "", title = "Malejąco" })
                </td>
                <td colspan="2">
                    @Html.ActionLink("↑", "Index", new { sortOrder = "email_desc", currentFilter = ViewBag.CurrentFilter }
                    , new { Class = "Akcja", title = "Rosnąco" })
                    @Html.ActionLink("↓", "Index", new { sortOrder = "email_asc", currentFilter = ViewBag.CurrentFilter }
                    , new { Class = "Akcja", title = "Malejąco" })
                </td>

                @foreach (var item in Model)
                {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Imie)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nazwisko)
                    </td>
                    <td>
                        @if (item.Zdjecie != null)
                        {
                            <img src="~/Obrazki/@Html.DisplayFor(modelItem => item.Zdjecie)" id="myImg" class="rozmiar" />
                            <div id="myModal" class="modal">
                                <span class="close">&times;</span>
                                <img class="modal-content" id="img01">
                                <div id="caption"></div>
                            </div>
                        }
                    </td>
                    <td>
                        @Html.DisplayFor(model => item.NrTelefonu)
                    </td>
                    <td>
                        @Html.DisplayFor(model => item.Email)
                    </td>
                    <td>
                        @if ((User.Identity.GetUserName() == item.Email && User.Identity.IsAuthenticated)
                        || User.IsInRole("Administrator"))
                        {
                            @Html.ActionLink(" ", "Edit", new { id = item.ID }, new { @class = "btn btn-primary glyphicon glyphicon-edit", title="Edycja" }) <span> | </span>
                            @Html.ActionLink(" ", "Delete", new { id = item.ID }, new { @class = "btn btn-info glyphicon glyphicon-trash", title="Kasuj" }) <span> | </span>
                        }

                        @Html.ActionLink(" ", "Details", new { id = item.ID }, new { @class = "btn btn-success glyphicon glyphicon-align-justify", title="Więcej" })

                    </td>



                </tr>
                }

            </table>
            <br />

            <div id="pagination-postion">
                <div class="count">
                    Strona @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) z @Model.PageCount
                </div>
                @Html.PagedListPager(Model, page => Url.Action("Index",
                        new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))
            </div>

            <div class="text-center">
                Wszystkich: @Model.TotalItemCount
            </div>

        </div>
}
else
{
    <div>Nic nie znaleziono</div>
}

<link href="~/Content/PginationPosition.css" rel="stylesheet" />