GabinetStomatologiczny/GabinetStomatologiczny/Controllers/PacjentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GabinetStomatologiczny.DAL;
using GabinetStomatologiczny.Models;
using PagedList;
using GabinetStomatologiczny.DAO.Models;
using GabinetStomatologiczny.Utils;
using GabinetStomatologiczny.Services;
using System.Threading.Tasks;
using System.Drawing.Printing;

namespace GabinetStomatologiczny.Controllers
{
    [Authorize]
    public class PacjentsController : BaseController
    {

        private readonly IPacjentsService pacjentsService = null;
        private readonly ISortPacjentService sortPacjentService = null;
        private readonly ISugestionService sugestionService = null;

        public PacjentsController(IPacjentsService pacjentsService, 
            ISortPacjentService sortPacjentService, 
            ISugestionService sugestionService,
            GabinetContext db):base(db)
        {
            this.pacjentsService = pacjentsService;
            this.sortPacjentService = sortPacjentService;
            this.sugestionService = sugestionService;
        }

        // GET: Pacjents
        public ActionResult Index(PacjentSort pacjentSort)
        {
            ViewBag.CurrentSort = pacjentSort.sortOrder;
            if (string.IsNullOrEmpty(pacjentSort.searchString))
            {
                pacjentSort.searchString = pacjentSort.currentFilter;
            }

            ViewBag.CurrentFilter = pacjentSort.searchString;
            var pacjent = this.sortPacjentService.SortAndPaginate(pacjentSort);
            ViewBag.ActiveClass = this.sortPacjentService.RodzajSort;


            if (Request.IsAjaxRequest())
            {
                return PartialView("_PatiensParts", pacjent);

            }
            return View(pacjent);
        }

        public ActionResult Sugestions(Sugestion sugestion)
        {
            var list = this.sugestionService.SugestionPacjent(sugestion);

            
            return Json(list, JsonRequestBehavior.AllowGet);
        }

        // GET: Pacjents/Details/5
        public async Task <ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pacjent pacjent = await this.pacjentsService.Find(id);
            if (pacjent == null)
            {
                return HttpNotFound();
            }
            return View(pacjent);
        }

        // GET: Pacjents/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Pacjents/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Imie,DrugieImie,Nazwisko,Pesel,Plec,DataUrodzenia,NrTelefonu,Email,Miejscowosc,Kod,Ulica,Wojewodztwo,Kraj,OdzialNfz,DataRejestracji")] Pacjent pacjent)
        {
            if (ModelState.IsValid)
            {
                pacjent.DataRejestracji = DateTime.Now;
                this.pacjentsService.CreatePacjnt(pacjent);
                return RedirectToAction("Index");
            }

            return View(pacjent);
        }

        // GET: Pacjents/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pacjent pacjent = await this.pacjentsService.Find(id);
      
            if (pacjent == null)
            {
                return HttpNotFound();
            }
            return View(pacjent);
        }

        // POST: Pacjents/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Imie,DrugieImie,Nazwisko,Pesel,Plec,DataUrodzenia,NrTelefonu,Email,Miejscowosc,Kod,Ulica,Wojewodztwo,Kraj,OdzialNfz,DataRejestracji")] Pacjent pacjent)
        {
            if (ModelState.IsValid)
            {
                this.pacjentsService.Edit(pacjent);
                TempData["editPacjent"] = "done";
                return RedirectToAction("Index");
            }
            return View(pacjent);
        }

        // GET: Pacjents/Delete/5
        public async Task <ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pacjent pacjent = await this.pacjentsService.Find(id);
            if (pacjent == null)
            {
                return HttpNotFound();
            }
            return View(pacjent);
        }

        // POST: Pacjents/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task <ActionResult> DeleteConfirmed(int id)
        {
            Pacjent pacjent = await this.pacjentsService.Find(id);
            this.pacjentsService.Remove(pacjent);
            return RedirectToAction("Index");
        }

    }
}

GabinetStomatologiczny/GabinetStomatologiczny/Controllers/WizytasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GabinetStomatologiczny.DAL;
using GabinetStomatologiczny.Models;
using GabinetStomatologiczny.DAO.Models;
using GabinetStomatologiczny.Utils;
using System.Diagnostics;
using AutoMapper;
using static GabinetStomatologiczny.Startup;
using System.Threading.Tasks;
using Nexmo.Api;
using System.Security.Claims;
using GabinetStomatologiczny.Services;

namespace GabinetStomatologiczny.Controllers
{
    public class WizytasController : BaseController
    {
        private IUserRoleService _userRoleService;
        public WizytasController(GabinetContext db, IUserRoleService userRoleService) : base(db)
        {
            this._userRoleService = userRoleService;
        }

        // GET: Wizytas
        public ActionResult Index()
        {
            var userIdentity = (ClaimsIdentity)User.Identity;
            var claims = userIdentity.Claims;
            var roleClaimType = userIdentity.RoleClaimType;
            var roles = claims.Where(c => c.Type == ClaimTypes.Role).ToList();
           
            return View();
        }

        public async Task<JsonResult> GetEvents(string searchQuery)
        {
           
            var eventsQuery = db.Wizyta.AsQueryable();

            if (!string.IsNullOrEmpty(searchQuery))
            {
                eventsQuery = eventsQuery.Where(p => p.Tytul.Contains(searchQuery));
            }

            var isLogedin = User.Identity.IsAuthenticated;
            var r = this._userRoleService.GetUserRole((ClaimsIdentity)User.Identity);
            var u = new { Name = User.Identity.Name  };
            var events = await eventsQuery.Select(_ =>
           new
           {
               _.ID,
               _.Koniec,
               _.Poczatek,
               Tytul = isLogedin ? _.Tytul : "*",
               p = isLogedin ?
                    new
                    {
                        _.Pacjent.NrTelefonu,
                        _.Pacjent.Email,
                        activeUser = new { u.Name },
                        role = r
                    } : 
                    null,
           }).ToListAsync();

            
            
            return new JsonResult { Data = events, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }

        public JsonResult Sugestions(string term)
        {
            var events = db.Wizyta.ToList().
                Where(p => p.Tytul.ToLower().
                Contains(term.ToLower()) &&
                p.Poczatek >= DateTime.Now).
                OrderBy(p => p.Poczatek).
                Take(5).
                Select(p => new { label = p.Tytul + " " + p.Poczatek.ToString("dd.MMM.yyyy, H:mm") });

            events = events.Count() == 0 ? events.DefaultIfEmpty().Select(p => new { label = "Nie jesteś zapisany" }).Take(1) : events;

            return Json(events, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult Sms(string to, string text)
        {
            var status = false;
            var results = SMS.Send(new SMS.SMSRequest
            {
                from = Configuration.Instance.Settings["appsettings:NEXMO_FROM_NUMBER"],
                to = to,
                text = text
              
            });
            status = true;
            return Json(status, JsonRequestBehavior.AllowGet);
        }


        [HttpPost]
        public JsonResult SaveEvent(Wizyta w)
        {
            var status = false;
            try
            {
                if (w.ID > 0)
                {
                    var v = db.Wizyta.Where(a => a.ID == w.ID).FirstOrDefault();
                    if (v != null)
                    {
                        w.LekarzID = v.LekarzID;
                        w.PacjentID = v.PacjentID;
                        if (!string.IsNullOrEmpty(v.Tytul))
                        {
                            w.Tytul = v.Tytul;
                        }
                        var m = Mapper.Map<Wizyta, Wizyta>(w, v);
                        if (string.IsNullOrEmpty(m.Tytul))
                        {
                            m.Tytul = db.Pacjent.Where(p => p.Email == User.Identity.Name).Select(p => p.Imie + " " + p.Nazwisko).FirstOrDefault();
                        }
                       
                        db.Entry(m).State = EntityState.Modified;
                    }

                }
                else
                {
                    w.PacjentID = db.Pacjent.Where(p => p.Email == User.Identity.Name).Select(p => p.ID).FirstOrDefault();
                    w.LekarzID = db.Lekarz.Select(p => p.ID).FirstOrDefault();
                    var m = Mapper.Map<Wizyta, Wizyta>(w);
                   
                    if (m.Tytul != null)
                    {
                        var pacjent = db.Pacjent.Where(_ => (_.Imie + " " + _.Nazwisko).Equals(w.Tytul) ).FirstOrDefault();
                        m.PacjentID = pacjent.ID;
                    }else
                    {
                        m.Tytul = db.Pacjent.Where(p => p.Email == User.Identity.Name).Select(p => p.Imie + " " + p.Nazwisko).FirstOrDefault();
                    }
                  
                    
                    db.Wizyta.Add(m);

                }
                status = true;
                db.SaveChanges();
            }
            catch (Exception)
            {

            }

            return new JsonResult { Data = new { status } };
        }

        [HttpPost]
        public JsonResult DeleteEvent(Wizyta w)
        {
            var status = false;

            var v = db.Wizyta.Where(a => a.ID == w.ID).FirstOrDefault();
            if (v != null)
            {
                db.Wizyta.Remove(v);
                db.SaveChanges();
                status = true;
            }

            return new JsonResult { Data = new { status = status } };
        }


        // GET: Wizytas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Wizyta wizyta = db.Wizyta.Find(id);
            if (wizyta == null)
            {
                return HttpNotFound();
            }
            return View(wizyta);
        }

        // GET: Wizytas/Create
        public ActionResult Create()
        {
            ViewBag.LekarzID = new SelectList(db.Lekarz, "ID", "Imie");
            ViewBag.PacjentID = new SelectList(db.Pacjent, "ID", "Imie");
            return View();
        }

        // POST: Wizytas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,LekarzID,PacjentID,Data")] Wizyta wizyta)
        {
            if (ModelState.IsValid)
            {
                db.Wizyta.Add(wizyta);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.LekarzID = new SelectList(db.Lekarz, "ID", "Imie", wizyta.LekarzID);
            ViewBag.PacjentID = new SelectList(db.Pacjent, "ID", "Imie", wizyta.PacjentID);
            return View(wizyta);
        }

        // GET: Wizytas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Wizyta wizyta = db.Wizyta.Find(id);
            if (wizyta == null)
            {
                return HttpNotFound();
            }
            ViewBag.LekarzID = new SelectList(db.Lekarz, "ID", "Imie", wizyta.LekarzID);
            ViewBag.PacjentID = new SelectList(db.Pacjent, "ID", "Imie", wizyta.PacjentID);
            return View(wizyta);
        }

        // POST: Wizytas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,LekarzID,PacjentID,Data")] Wizyta wizyta)
        {
            if (ModelState.IsValid)
            {
                db.Entry(wizyta).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.LekarzID = new SelectList(db.Lekarz, "ID", "Imie", wizyta.LekarzID);
            ViewBag.PacjentID = new SelectList(db.Pacjent, "ID", "Imie", wizyta.PacjentID);
            return View(wizyta);
        }

        // GET: Wizytas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Wizyta wizyta = db.Wizyta.Find(id);
            if (wizyta == null)
            {
                return HttpNotFound();
            }
            return View(wizyta);
        }

        // POST: Wizytas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Wizyta wizyta = db.Wizyta.Find(id);
            db.Wizyta.Remove(wizyta);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GabinetStomatologiczny/GabinetStomatologiczny/Views/Wizytas/Create.cshtml
@model GabinetStomatologiczny.DAO.Models.Wizyta

@{
    ViewBag.Title = "Create";
}

<script src="~/Scripts/jquery-1.12.4.js"></script>
<script src="~/Scripts/jquery-ui-1.12.1.js"></script>
<script src="~/Scripts/datepicker-pl.js"></script>
<link href="~/Content/Kalendarz.css" rel="stylesheet" />

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Wizyta</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.LekarzID, "LekarzID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("LekarzID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.LekarzID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PacjentID, "PacjentID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PacjentID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PacjentID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Poczatek, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="kalendarz">
                    <span class="glyphicon-calendar kalendarz"></span>
                    @Html.EditorFor(model => model.Poczatek, new { htmlAttributes = new { @class = "form-control" } })
                </div>
                @Html.ValidationMessageFor(model => model.Poczatek, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

GabinetStomatologiczny/GabinetStomatologiczny/Views/Wizytas/Delete.cshtml
@model GabinetStomatologiczny.DAO.Models.Wizyta

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Wizyta</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Lekarz.Imie)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Lekarz.Imie)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Pacjent.Imie)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pacjent.Imie)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Data)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Data)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

GabinetStomatologiczny/GabinetStomatologiczny/Views/Wizytas/Details.cshtml
@model GabinetStomatologiczny.DAO.Models.Wizyta

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Wizyta</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Lekarz.Imie)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Lekarz.Imie)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Pacjent.Imie)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pacjent.Imie)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

GabinetStomatologiczny/GabinetStomatologiczny/Views/Wizytas/Index.cshtml
@model IEnumerable<GabinetStomatologiczny.DAO.Models.Wizyta>
@{
    ViewBag.Title = "Wizyty";
    ViewBag.Active = "Wizytas";
}
<link href="//cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.4.0/fullcalendar.min.css" rel="stylesheet" />
<link href="//cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.4.0/fullcalendar.print.css" rel="stylesheet" media="print" />
<link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/css/bootstrap-datetimepicker.min.css" rel="stylesheet" />
<link href="~/Content/themes/base/jquery-ui.css" rel="stylesheet" />
<link href="~/Content/Wizyta.css" rel="stylesheet" />
<link href="~/Content/Wyszukiwarka.css" rel="stylesheet" />

<div id="saveDatabaseInfo"></div>

<div class="ladowanie"></div>

<!--Search form-->
<div class="text-right" id="aktualnyCzas"></div>

@if (User.Identity.IsAuthenticated)
{
    <div class="form-group">
        <form id="wyslij" class="wyszukiwarka" action="@Url.Action("GetEvents")" method="get" data-ajax="true">
            <input type="text" id="searchQuery" name="searchQuery"
                   data-autocomplete-source="@Url.Action("Sugestions")" placeholder="Sprawdź czy jesteś zapisany"
                   class="form-control" />
        <span id="searchclear" class="glyphicon glyphicon-remove-circle kasujText"></span>
        </form>
    </div>
}

<!--End search form-->
<div id="calender"></div>
<!--About-->
<div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header modal-info">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h1 style="text-align:center;">Informacje o wizycie</h1>
                <h4 class="modal-title text-center"><span id="eventTitle"></span></h4>
            </div>
            <div class="modal-body">
                <p id="pDetails"></p>
                @if (User.IsInRole("Pacjent") ||
             User.IsInRole("Administrator") ||
             User.IsInRole("Lekarz"))
                {
                    {
                        <div id="action">
                            <button id="btnDelete" class="btn btn-danger btn-sm pull-right">
                                <span class="glyphicon glyphicon-remove"></span> Kasuj
                            </button>
                            <button id="btnEdit" class="btn btn-default btn-sm pull-right" style="margin-right: 5px;">
                                <span class="glyphicon glyphicon-pencil"></span> Edytuj
                            </button>
                            @if (User.IsInRole("Administrator"))
                            {
                                <button id="btnSms" class="btn btn-primary btn-sm pull-right" style="margin-right: 5px;">
                                    <span class="glyphicon glyphicon-pencil"></span> Sms
                                </button>
                            }
                        </div>
                    }
                }
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-warning" data-dismiss="modal">Zamknij</button>
            </div>
        </div>
    </div>
</div>



<!--End about-->
@if (User.Identity.IsAuthenticated && User.IsInRole("Pacjent")
                                         || User.IsInRole("Administrator")
                                         || User.IsInRole("Lekarz"))
{
    <!--Eror-->
    <div id="myModalError" class="modal fade" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header modal-warning">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h1 class="modal-title text-center"><span id="eventTitle">Błąd</span></h1>
                </div>
                <div class="modal-body">
                    <h4 style="color:red;">Wybrana data musi być późniejsza</h4>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-warning" data-dismiss="modal">Zamknij</button>
                </div>
            </div>
        </div>
    </div>
    <!--End Eror-->

    <!--Send sms-->
    <div id="myModalSendSms" class="modal fade" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header modal-info">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title text-center">Wyslij sms</h4>
                </div>
                <div class="modal-body">
                    <form class="col-md-12 form-horizontal">
                        <label for="inputDo">Do : </label>
                        <input type="text" class="form-control" id="inputDo" placeholder="Nr telefonu" />
                        <div id="errorSmsTo"></div>
                        <label for="inputDo">Wiadomość : </label>
                        <textarea type="text" class="form-control" id="inputWiadomosc" placeholder="Wiadomość"></textarea>
                        <div id="errorSmsWiadom"></div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Zamknij</button>
                    <button type="button" id="btnSmsSend"
                            class="btn btn-success float-right" data-loading-text="Wysyłanie...">
                        Wyslij
                    </button>
                </div>
            </div>
        </div>
    </div>
    <!--End send sms-->

     <!-- Delete coonfirm modal -->
    <div class="modal fade" id="deleteConfirmModal" role="dialog">
        <div class="modal-dialog modal-sm">
            <div class="modal-content">
                <div class="modal-header modal-danger">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Kasowanie</h4>
                </div>
                <div class="modal-body">
                    <p>Czy napewno chcesz skasować ?</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Zamknij</button>
                    <button type="button" class="btn btn-danger" id="kasujElement" data-dismiss="modal" data-loading-text="Kasowanie...">Kasuj</button>
                </div>
            </div>
        </div>
    </div>
    <!--  END Delete coonfirm modal -->
    <!--Add Edit-->
    <div id="myModalSave" class="modal fade" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header modal-info">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title text-center">Zapisz</h4>
                </div>
                <div class="modal-body">
                    <form class="col-md-12 form-horizontal" data-ajax="true">
                        <input type="hidden" id="hdEventID" value="0" />
                        <div class="form-group">
                            <label>Początek</label>
                            <div class="input-group date" id="dtp1">
                                <input type="text" id="txtStart" class="form-control" />
                                <span class="input-group-addon">
                                    <span class="glyphicon glyphicon-calendar"></span>
                                </span>
                            </div>
                        </div>
                        @if (User.IsInRole("Administrator") || User.IsInRole("Lekarz"))
                        {
                            <div class="form-group">
                                <label>Imię nazwisko</label>
                                <div class="input-group" id="dtp2">
                                    <input type="text" id="tytul"
                                           data-autocomplete-source="@Url.Action("Sugestions","Pacjents")"
                                           class="form-control"
                                           placeholder="Wyszukaj pacjęta" />
                                    <span class="input-group-addon">
                                        <span class="glyphicon glyphicon-user"></span>
                                    </span>
                                </div>
                            </div>
                        }
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-warning" data-dismiss="modal">Zamknij</button>
                    <button type="button" id="btnSave"
                            class="btn btn-success float-right" data-loading-text="Zapisywanie...">
                        Zapisz
                    </button>
                </div>
            </div>
        </div>
    </div>
    <!--End Add Edit-->
}
@section scripts{
    <script src="~/Scripts/locale/pl.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js"></script>
    <script src="~/Scripts/jquery-ui-1.12.1.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script src="~/Content/script/KalendarzWizyt.js"></script>
    <script src="~/Content/script/AutoComplete.js"></script>
    <script src="~/Content/script/AutoComplSearchWizyta.js"></script>
}